repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Ruff version.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      # Run the linter.
      - id: ruff-check
        # args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
      - id: build-docs
        #   args: ['--cache-dir', 'docs/_build/doctrees', '--html-dir', 'docs/_build/html', '--source-dir', 'docs/source']
        args:
          [
            "--cache-dir",
            "docs/_build/doctrees",
            "--html-dir",
            "docs/_build/html",
            "--source-dir",
            "kentraBOT",
          ]
        language_version: python3
